### ISSUE TITLE
CREATE VIEW statement returns no Rows{}, causes bq-emulator to hang. #28

### ISSUE THREAD

**Issue by yaronneuman** [goccy/go-zetasqlite#108]
The QueryContext of CreateViewStmtAction returns nil even if there is no Error
It should return an empty Rows{} struct to signal callers that the action successfuly completed with no errors.

another option is to change callers to accept nil, nil as valid non-error result, but I think it will be much harder.

see also goccy/bigquery-emulator#188

**Comment by goccy** [comment]
This problem has been fixed
