### ISSUE TITLE
QUALIFY clause without WHERE or GROUP_BY or HAVING

### ISSUE THREAD

**Issue by anugna21** [goccy/go-zetasqlite#123]
Hello,

Currently seeing this error for queries with QUALIFY clause without a WHERE:

`INVALID_ARGUMENT: QUALIFY clause must be used in conjunction with WHERE or GROUP BY or HAVING clause `

Looks like there is a workaround for this in zetasql as discussed here: https://github.com/google/zetasql/issues/124

Any plans on adopting this change  to parse queries executed from BigQuery?

**Comment by ohaibbq** [comment]
@goccy Could you assign this to me?
