### ISSUE TITLE
Hyperloglog++

### ISSUE THREAD

**Issue by nielsbasjes** [goccy/go-zetasqlite#22]
I noticed that the HLL functions have not yet been implemented.
https://github.com/goccy/go-zetasqlite#hyperloglog-functions

I only wanted to make sure you are aware that Google has opensourced their Java implementation of the algorithms and encodings:  https://github.com/google/zetasketch

I suspect this may serve your implementation efforts as a reference to build/test against.

**Comment by goccy** [comment]
Thank you for submitting issue !
I will support Hyperloglog++ functions by https://github.com/axiomhq/hyperloglog in the future .

**Comment by nielsbasjes** [comment]
Cool, I wanted to you to know about this implementation because with BigQuery I can precompute a partial HLL sketch (using the mentioned Java library) and insert that into BigQuery.

That allows me to run a query in BigQuery (with filters, group by, etc) and then determine the estimated cardinality.

The key point is that this zetasketch library is not only an HLL implementation, but more importantly an implementation that is both mathmatically and binary compatible with BigQuery.

See also: https://cloud.google.com/blog/products/data-analytics/using-hll-speed-count-distinct-massive-datasets
