### ISSUE TITLE
Test is not working in subdirectory

### ISSUE THREAD

**Issue by kitagry** [goccy/go-zetasqlite#36]
The following error occurred. In [workflows/go.yaml#L47](https://github.com/goccy/go-zetasqlite/blob/main/.github/workflows/go.yml#L47), go test root repository only.

I think it should be changed from `go test ./` to `go test ./...`.  You don't need `internal/value_test.go` already, do you?

```
❯ go test ./...
# github.com/goccy/go-zetasqlite/internal [github.com/goccy/go-zetasqlite/internal.test]
internal/value_test.go:21:6: undefined: timestampRe
internal/value_test.go:24:6: undefined: timestampRe
ok      github.com/goccy/go-zetasqlite  0.941s
FAIL    github.com/goccy/go-zetasqlite/internal [build failed]
FAIL
```

**Comment by goccy** [comment]
Thank  you for the reporting ! I fixed this problem with #37
